workflows:
  unity-ios-activate-and-build:
    name: Unity iOS: Activate Xcode Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      unity: 6000.0.7f1
      groups:
        - unity_credentials           # UNITY_SERIAL, UNITY_EMAIL, UNITY_PASSWORD
      xcode: "16.4"
      vars:
        UNITY_IOS_DIR: ios
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"

    scripts:
      - name: Activate Unity License
        script: |
          set -euo pipefail
          # autodetect UNITY_HOME from ProjectVersion.txt if not provided
          if [ -z "${UNITY_HOME:-}" ]; then
            if [ -f "ProjectSettings/ProjectVersion.txt" ]; then
              UNITY_VERSION="$(awk -F': ' '/m_EditorVersion:/{print $2}' ProjectSettings/ProjectVersion.txt)"
              export UNITY_HOME="/Applications/Unity/Hub/Editor/${UNITY_VERSION}/Unity.app"
            fi
          fi
          echo "Using UNITY_HOME=${UNITY_HOME:?UNITY_HOME is not set}"
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode -quit -logFile -nographics \
            -serial "${UNITY_SERIAL?}" \
            -username "${UNITY_EMAIL?}" \
            -password "${UNITY_PASSWORD?}"

      - name: Generate Xcode project from Unity
        script: |
          set -euo pipefail
          echo "Using UNITY_HOME=${UNITY_HOME:?}"
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode -quit -logFile -nographics \
            -projectPath . \
            -executeMethod "BuildScript.BuildIos"

      - name: Build Xcode project (compile only)
        script: |
          set -euo pipefail
          cd "$UNITY_IOS_DIR"
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -derivedDataPath "$HOME/Library/Developer/Xcode/DerivedData/UnityBuild" \
            build

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/UnityBuild/Build/Products/Release-iphoneos/*.app
