workflows:
  unity-ios-activate-and-build:
    name: "Unity iOS: Activate Xcode Build"
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      unity: 6000.0.37f1
      groups:
        - unity_credentials           # UNITY_SERIAL, UNITY_EMAIL, UNITY_PASSWORD
      xcode: "16.4"
      vars:
        UNITY_IOS_DIR: ios
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"

    scripts:
      - name: Activate Unity License
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile \
            -serial ${UNITY_SERIAL?} \
            -username ${UNITY_EMAIL?} \
            -password ${UNITY_PASSWORD?}

      - name: Generate the Xcode project from Unity
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode \
            -quit \
            -logFile \
            -projectPath . \
            -executeMethod BuildScript.$BUILD_SCRIPT \
            -nographics

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/UnityBuild/Build/Products/Release-iphoneos/*.app
